name: Swift CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      # Закомментированы шаги сборки и тестирования
      # - name: Build and Test
      #   run: xcodebuild -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.5' build test

      - name: Run Tests
        run: |
          echo "Running tests..."
          xcodebuild -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test
          exit 1  # Искусственно вызываем ошибку для тестирования уведомлений

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify Slack on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
        with:
          message: "❌ Build failed in repository ${{ github.repository }} for commit ${{ github.sha }}. Check details: ${{ github.run_url }}"

      - name: Notify Slack on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: 'GitHub Actions'
          SLACK_ICON_EMOJI: ':github:'
        with:
          message: "✅ Build succeeded in repository ${{ github.repository }} for commit ${{ github.sha }}. Check details: ${{ github.run_url }}"

      - name: Notify Telegram on Failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id=${{ env.CHAT_ID }} -d text="❌ Build failed in repository: ${{ github.repository }}. Commit: ${{ github.sha }}. Check details: ${{ github.run_url }}"

      - name: Notify Telegram on Success
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id=${{ env.CHAT_ID }} -d text="✅ Build succeeded in repository: ${{ github.repository }}. Commit: ${{ github.sha }}. Check details: ${{ github.run_url }}"
