name: CI with Telegram Notifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - name: Run Tests
        run: |
          echo "Running tests..."
          xcodebuild -scheme MyApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' test
          exit 1  # Искусственно вызываем ошибку для тестирования уведомлений

      - name: Check Test Results
        if: failure()
        run: echo "Tests failed"

      - name: Notify Telegram on Failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: 546454208
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id=${{ env.CHAT_ID }} -d text="❌ Build failed in repository: ${{ github.repository }}. Commit: ${{ github.sha }}. Check details: ${{ github.run_url }}"
